AWSTemplateFormatVersion: '2010-09-09'
Description: Public Subnets
Parameters:
  VpcStackName:
    Type: String
Resources:
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VpcStackName}-VpcId'
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: eu-west-2a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: cicd-ecr-public-subnet-1
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VpcStackName}-VpcId'
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: eu-west-2b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: cicd-ecr-public-subnet-2
Outputs:
  PublicSubnet1Id:
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet1'
  PublicSubnet2Id:
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet2'
  SubnetList:
    Value: !Join [',', [!Ref PublicSubnet1, !Ref PublicSubnet2]]
    Export:
      Name: !Sub '${AWS::StackName}-SubnetList'
