AWSTemplateFormatVersion: '2010-09-09'
Description: Main CloudFormation Stack Orchestrator
Parameters:
  ECRImageUri:
    Type: String
    Description: ECR Repository URI for the Docker image
  TemplatesBucket:
    Type: String
    Description: S3 Bucket name where CloudFormation templates are stored
Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: cicd-ecr-vpc-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/vpc.yaml'
  
  # Internet Gateway Stack
  IGWStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      StackName: cicd-ecr-igw-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/igw.yaml'
      Parameters:
        VpcStackName: cicd-ecr-vpc-stack
  
  # Subnets Stack
  SubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      StackName: cicd-ecr-subnets-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/subnets.yaml'
      Parameters:
        VpcStackName: cicd-ecr-vpc-stack
  
  # Route Table Stack
  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SubnetsStack
    Properties:
      StackName: cicd-ecr-routetable-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/route-table.yaml'
      Parameters:
        VpcStackName: cicd-ecr-vpc-stack
        SubnetsStackName: cicd-ecr-subnets-stack
  
  # Route Stack
  RouteStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IGWStack
      - RouteTableStack
    Properties:
      StackName: cicd-ecr-route-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/route.yaml'
      Parameters:
        RouteTableStackName: cicd-ecr-routetable-stack
        IGWStackName: cicd-ecr-igw-stack
  
  # ALB Security Group Stack
  ALBSGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      StackName: cicd-ecr-alb-sg-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/security/alb-sg.yaml'
      Parameters:
        VpcStackName: cicd-ecr-vpc-stack
  
  # ECS Security Group Stack
  ECSSGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - ALBSGStack
    Properties:
      StackName: cicd-ecr-ecs-sg-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/security/ecs-sg.yaml'
      Parameters:
        VpcStackName: cicd-ecr-vpc-stack
        ALBSGStackName: cicd-ecr-alb-sg-stack
  
  # ECR Stack
  ECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: cicd-ecr-ecr-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/ecr.yaml'
  
  # Logs Stack
  LogsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: cicd-ecr-logs-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/logs.yaml'
  
  # IAM Stack
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: cicd-ecr-iam-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/iam.yaml'
  
  # Cluster Stack
  ClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      StackName: cicd-ecr-cluster-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/cluster.yaml'
  
  # ALB Stack
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SubnetsStack
      - ALBSGStack
    Properties:
      StackName: cicd-ecr-alb-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/alb.yaml'
      Parameters:
        SubnetsStackName: cicd-ecr-subnets-stack
        ALBSGStackName: cicd-ecr-alb-sg-stack
  
  # Target Group Stack
  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      StackName: cicd-ecr-targetgroup-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/target-group.yaml'
      Parameters:
        VpcStackName: cicd-ecr-vpc-stack
  
  # Task Definition Stack
  TaskDefStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ECRStack
      - LogsStack
      - IAMStack
    Properties:
      StackName: cicd-ecr-taskdef-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/taskdef.yaml'
      Parameters:
        ECRRepoUri: !Ref ECRImageUri
        LogGroupStackName: cicd-ecr-logs-stack
        IAMStackName: cicd-ecr-iam-stack
  
  # ECS Service Stack
  ServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ClusterStack
      - TaskDefStack
      - TargetGroupStack
      - SubnetsStack
      - ECSSGStack
    Properties:
      StackName: cicd-ecr-service-stack
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/service.yaml'
      Parameters:
        ClusterStackName: cicd-ecr-cluster-stack
        TaskDefStackName: cicd-ecr-taskdef-stack
        TargetGroupStackName: cicd-ecr-targetgroup-stack
        SubnetsStackName: cicd-ecr-subnets-stack
        ECSSecurityGroupStackName: cicd-ecr-ecs-sg-stack
Outputs:
  ALBDNSName:
    Description: ALB DNS Name
    Value: !GetAtt ALBStack.Outputs.ALBDNSName
    Export:
      Name: cicd-ecr-alb-dns
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRStack.Outputs.ECRRepositoryUri
    Export:
      Name: cicd-ecr-repo-uri
  ServiceName:
    Description: ECS Service Name
    Value: !GetAtt ServiceStack.Outputs.ServiceName
    Export:
      Name: cicd-ecr-service-name
