AWSTemplateFormatVersion: '2010-09-09'
Description: Main CloudFormation Stack Orchestrator

Parameters:
  ECRImageUri:
    Type: String
    Description: ECR Repository URI for the Docker image
  TemplatesBucket:
    Type: String
    Description: S3 Bucket name where CloudFormation templates are stored

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/vpc.yaml'

  # Internet Gateway Stack
  IGWStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/igw.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack

  # Subnets Stack
  SubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/subnets.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack

  # Route Table Stack
  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/route-table.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack
        SubnetsStackName: !Ref SubnetsStack

  # Route Stack
  RouteStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IGWStack
      - RouteTableStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/vpc/route.yaml'
      Parameters:
        RouteTableStackName: !Ref RouteTableStack
        IGWStackName: !Ref IGWStack

  # ALB Security Group Stack
  ALBSGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/security/alb-sg.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack

  # ECS Security Group Stack
  ECSSGStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - ALBSGStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/security/ecs-sg.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack
        ALBSGStackName: !Ref ALBSGStack

  # ECR Stack
  ECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/ecr.yaml'

  # Logs Stack
  LogsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/logs.yaml'

  # IAM Stack
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/iam.yaml'

  # Cluster Stack
  ClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/cluster.yaml'

  # ALB Stack
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SubnetsStack
      - ALBSGStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/alb.yaml'
      Parameters:
        SubnetsStackName: !Ref SubnetsStack
        ALBSGStackName: !Ref ALBSGStack

  # Target Group Stack
  TargetGroupStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/target-group.yaml'
      Parameters:
        VpcStackName: !Ref VPCStack

  # Task Definition Stack
  TaskDefStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ECRStack
      - LogsStack
      - IAMStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/taskdef.yaml'
      Parameters:
        ECRRepoUri: !Ref ECRImageUri
        LogGroupStackName: !Ref LogsStack
        IAMStackName: !Ref IAMStack

  # ECS Service Stack
  ServiceStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ClusterStack
      - TaskDefStack
      - TargetGroupStack
      - SubnetsStack
      - ECSSGStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplatesBucket}/templates/ecs/service.yaml'
      Parameters:
        ClusterStackName: !Ref ClusterStack
        TaskDefStackName: !Ref TaskDefStack
        TargetGroupStackName: !Ref TargetGroupStack
        SubnetsStackName: !Ref SubnetsStack
        ECSSecurityGroupStackName: !Ref ECSSGStack

Outputs:
  ALBDNSName:
    Description: ALB DNS Name
    Value: !GetAtt ALBStack.Outputs.ALBDNSName
    Export:
      Name: cicd-ecr-alb-dns
  ECRRepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRStack.Outputs.ECRRepositoryUri
    Export:
      Name: cicd-ecr-repo-uri
  ServiceName:
    Description: ECS Service Name
    Value: !GetAtt ServiceStack.Outputs.ServiceName
    Export:
      Name: cicd-ecr-service-name
