AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Delete
    Properties:
      RepositoryName:
        Fn::Join:
          - ''
          - - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 8
                  - !Split
                    - '/'
                    - !Ref AWS::StackId
            - !Sub '${AWS::Region}-repo'
      ImageScanningConfiguration:
        ScanOnPush: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ecr-repo'

Outputs:
  ECRRepositoryUri:
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepoUri'
  ECRRepositoryName:
    Value: !Ref ECRRepository
    Export:
      Name: !Sub '${AWS::StackName}-ECRRepoName'
