AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition
Parameters:
  ECRRepoUri:
    Type: String
    Description: ECR Repository URI
  LogGroupStackName:
    Type: String
    Description: CloudFormation stack name for logs
  IAMStackName:
    Type: String
    Description: CloudFormation stack name for IAM
Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cicd-ecr-app
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !ImportValue
        Fn::Sub: '${IAMStackName}-TaskExecutionRoleArn'
      ContainerDefinitions:
        - Name: app
          Image: !Sub '${ECRRepoUri}:latest'
          Essential: true
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue
                Fn::Sub: '${LogGroupStackName}-LogGroupName'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - python3 -c "import urllib.request; urllib.request.urlopen('http://localhost/'); exit(0)" || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
Outputs:
  TaskDefinitionArn:
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefArn'
  TaskDefinitionFamily:
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefFamily'
